/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.Customer.Customer;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 18577
 */
public class DeliveryManWorkAreaPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    private DefaultTableModel orderDirectoryTableModel;
    private DeliveryMan deliveryMan;
    
    public DeliveryManWorkAreaPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initorderDirectoryTableModel();
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecoSystem = business;
        
 
        deliveryMan = ecoSystem.getDeliveryManDirectory().getDeliveryManWithUserAccountId(userAccount.getUserAccountId());
        managerLabel.setText(deliveryMan.getName());
        
        populateTable();
    }
     private void initorderDirectoryTableModel() {
        orderDirectoryTableModel = new DefaultTableModel();
        
        orderDirectoryTableModel.addColumn(" Restaurant Name");
        orderDirectoryTableModel.addColumn(" Restaurant Admin Name");
        orderDirectoryTableModel.addColumn(" Pick up addregetss");
        orderDirectoryTableModel.addColumn(" Customer Name");
        orderDirectoryTableModel.addColumn(" Delivery address");
        orderDirectoryTableModel.addColumn(" Order Message");
        orderDirectoryTableModel.addColumn(" Order Status");


    }
    
    public void populateTable() {
        
        orderDirectoryTableModel.setRowCount(0);
        
        for(WorkRequest workRequest: userAccount.getWorkQueue().getWorkRequestList()) {
            
            Customer c = ecoSystem.getCustomerDirectory().getCustomerWithUserAccountId(workRequest.getSender().getUserAccountId());
            Restaurant r = ecoSystem.getRestaurantDirectory().getRestaurantWithUserAccountId(workRequest.getReceiver().getUserAccountId());
            
            
            String[] rowData = {
                r.getRestName(),
                r.getManagerName(),
                r.getRestLocation(),
                c.getName(),                
                c.getAddress(),
                workRequest.getMessage(),
                workRequest.getStatus()
            
            
            };
            orderDirectoryTableModel.addRow(rowData);
        
        
        }
        
    }


    /**
     * Creates new form DeliveryManWorkAreaPanel
     */
    public DeliveryManWorkAreaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hiLabel = new javax.swing.JLabel();
        managerLabel = new javax.swing.JLabel();
        deliveryDirLabel1 = new javax.swing.JLabel();
        delDirectoryScollPanel1 = new javax.swing.JScrollPane();
        orderDirTable = new javax.swing.JTable();
        menuItemName2 = new javax.swing.JLabel();
        orderStatusCombobox = new javax.swing.JComboBox<>();
        saveChangesButton = new javax.swing.JButton();

        hiLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hiLabel.setForeground(new java.awt.Color(0, 0, 102));
        hiLabel.setText("Hi, ");

        managerLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        managerLabel.setForeground(new java.awt.Color(0, 0, 102));
        managerLabel.setText(" ");

        deliveryDirLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel1.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel1.setText("Your Order Directory");

        orderDirTable.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        orderDirTable.setForeground(new java.awt.Color(0, 0, 102));
        orderDirTable.setModel(orderDirectoryTableModel);
        orderDirTable.setRowHeight(40);
        delDirectoryScollPanel1.setViewportView(orderDirTable);

        menuItemName2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName2.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName2.setText("Order Status:");

        orderStatusCombobox.setForeground(new java.awt.Color(0, 0, 102));
        orderStatusCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Picked Up", "Delivered", "Unreachable Customer" }));

        saveChangesButton.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        saveChangesButton.setForeground(new java.awt.Color(0, 0, 102));
        saveChangesButton.setText("Save");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(hiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(managerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deliveryDirLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(430, 430, 430))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(delDirectoryScollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(menuItemName2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(orderStatusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiLabel)
                    .addComponent(managerLabel))
                .addGap(18, 18, 18)
                .addComponent(deliveryDirLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderStatusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuItemName2))
                        .addGap(51, 51, 51)
                        .addComponent(saveChangesButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(delDirectoryScollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        // TODO add your handling code here:
        userAccount.getWorkQueue().getWorkRequestList().get(orderDirTable.getSelectedRow())
                .setStatus((String) orderStatusCombobox.getSelectedItem());
        populateTable();
        JOptionPane.showMessageDialog(null, "Order Status Updated Successfully");

      
    }//GEN-LAST:event_saveChangesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane delDirectoryScollPanel1;
    private javax.swing.JLabel deliveryDirLabel1;
    private javax.swing.JLabel hiLabel;
    private javax.swing.JLabel managerLabel;
    private javax.swing.JLabel menuItemName2;
    private javax.swing.JTable orderDirTable;
    private javax.swing.JComboBox<String> orderStatusCombobox;
    private javax.swing.JButton saveChangesButton;
    // End of variables declaration//GEN-END:variables
}
