/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.MenuItem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.stream.Collectors;

/**
 *
 * @author 18577
 */
public class RestAdminWorkAreaPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount userAccount;
    EcoSystem ecoSystem;
    DefaultTableModel menuDirectoryTableModel;
    Restaurant currentRestaurantWorkPanel;
     
    
    /** Creates new form AdminWorkAreaJPanel */
    public RestAdminWorkAreaPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem) {
        initMenuModel();

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecoSystem = ecoSystem;
        
        loadRestaurantValues();
        populateMenuItems();

      
        //valueLabel.setText();
    }
    
    private void loadRestaurantValues() {

        currentRestaurantWorkPanel = ecoSystem.getRestaurantDirectory()
                .getRestList().stream()
                .filter(restaurant ->
                    restaurant.getUserAccount().getUserAccountId().equals(userAccount.getUserAccountId())
                ).collect(Collectors.toList())
                .get(0);

        restaurantNameLabel.setText(currentRestaurantWorkPanel.getRestName());
        managerLabel.setText(currentRestaurantWorkPanel.getRestName());
    
    }

    private void populateMenuItems() {
        for(MenuItem menuItem: currentRestaurantWorkPanel.getMenulist()) {
            menuDirectoryTableModel.setRowCount(0);
            String[] rowData = {menuItem.getMenuItemName() , "$ " + String.valueOf(menuItem.getMenuItemPrice())};
            menuDirectoryTableModel.addRow(rowData);
        }

    }

    /**
     * Creates new form RestAdminWorkAreaPanel
     */
    public RestAdminWorkAreaPanel() {
        initMenuModel();
        initComponents();
    }
    private void initMenuModel() {
        menuDirectoryTableModel = new DefaultTableModel();
        menuDirectoryTableModel.addColumn("Item Name");
        menuDirectoryTableModel.addColumn("Item Price");
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restaurantNameLabel = new javax.swing.JLabel();
        hiLabel = new javax.swing.JLabel();
        managerLabel = new javax.swing.JLabel();
        adminScreenTabbedPane = new javax.swing.JTabbedPane();
        menuPanel = new javax.swing.JPanel();
        deliveryDirLabel = new javax.swing.JLabel();
        delDirectoryScollPanel = new javax.swing.JScrollPane();
        menuDirTable = new javax.swing.JTable();
        menuItemName = new javax.swing.JLabel();
        menuItemTextF = new javax.swing.JTextField();
        saveMenuItemsButton = new javax.swing.JButton();
        menuItemName1 = new javax.swing.JLabel();
        ageSlider = new javax.swing.JSlider();
        ageLabelValue = new javax.swing.JLabel();
        deleteMenuItemButton = new javax.swing.JButton();

        restaurantNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        restaurantNameLabel.setForeground(new java.awt.Color(0, 0, 102));
        restaurantNameLabel.setText(" ");

        hiLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hiLabel.setForeground(new java.awt.Color(0, 0, 102));
        hiLabel.setText("Hi, ");

        managerLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        managerLabel.setForeground(new java.awt.Color(0, 0, 102));
        managerLabel.setText(" ");

        adminScreenTabbedPane.setForeground(new java.awt.Color(0, 0, 102));
        adminScreenTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        deliveryDirLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel.setText("Menu Directory");

        menuDirTable.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        menuDirTable.setForeground(new java.awt.Color(0, 0, 102));
        menuDirTable.setModel(menuDirectoryTableModel);
        menuDirTable.setRowHeight(40);
        delDirectoryScollPanel.setViewportView(menuDirTable);

        menuItemName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName.setText("Item Name:");

        menuItemTextF.setForeground(new java.awt.Color(0, 0, 102));
        menuItemTextF.setText(" ");

        saveMenuItemsButton.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        saveMenuItemsButton.setForeground(new java.awt.Color(0, 0, 102));
        saveMenuItemsButton.setText("Save");
        saveMenuItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemsButtonActionPerformed(evt);
            }
        });

        menuItemName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName1.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName1.setText("Item Price:");

        ageSlider.setForeground(new java.awt.Color(0, 0, 102));
        ageSlider.setMaximum(2000);
        ageSlider.setMinimum(10);
        ageSlider.setMinorTickSpacing(1);
        ageSlider.setPaintLabels(true);
        ageSlider.setSnapToTicks(true);
        ageSlider.setToolTipText("");
        ageSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ageSliderStateChanged(evt);
            }
        });

        ageLabelValue.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        ageLabelValue.setForeground(new java.awt.Color(0, 0, 102));
        ageLabelValue.setText(" ");

        deleteMenuItemButton.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        deleteMenuItemButton.setForeground(new java.awt.Color(0, 0, 102));
        deleteMenuItemButton.setText("Delete");
        deleteMenuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deliveryDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delDirectoryScollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menuItemName1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveMenuItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(menuPanelLayout.createSequentialGroup()
                                        .addComponent(ageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(ageLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(menuPanelLayout.createSequentialGroup()
                                        .addGap(579, 579, 579)
                                        .addComponent(deleteMenuItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(menuItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(menuItemTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(508, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(deliveryDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delDirectoryScollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(deleteMenuItemButton)
                .addGap(18, 18, 18)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuItemName)
                    .addComponent(menuItemTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuItemName1)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(ageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ageLabelValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addComponent(saveMenuItemsButton)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        adminScreenTabbedPane.addTab("Manage Menu", menuPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restaurantNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(hiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(managerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(865, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(adminScreenTabbedPane)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restaurantNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiLabel)
                    .addComponent(managerLabel))
                .addContainerGap(852, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(122, Short.MAX_VALUE)
                    .addComponent(adminScreenTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveMenuItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemsButtonActionPerformed
        // TODO add your handling code here:

        String itemName = menuItemTextF.getText().trim();
        int price = Integer.valueOf(ageLabelValue.getText());

        currentRestaurantWorkPanel.addMenuItem(itemName, price);
        populateMenuItems();




    }//GEN-LAST:event_saveMenuItemsButtonActionPerformed

    private void ageSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ageSliderStateChanged
        // TODO add your handling code here:

        ageLabelValue.setText(Integer.toString(ageSlider.getValue()));
    }//GEN-LAST:event_ageSliderStateChanged

    private void deleteMenuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemButtonActionPerformed
        // TODO add your handling code here:

        int selected = menuDirTable.getSelectedRow();
        currentRestaurantWorkPanel.removeMenuItem(selected);
        populateMenuItems();
    }//GEN-LAST:event_deleteMenuItemButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane adminScreenTabbedPane;
    private javax.swing.JLabel ageLabelValue;
    private javax.swing.JSlider ageSlider;
    private javax.swing.JScrollPane delDirectoryScollPanel;
    private javax.swing.JButton deleteMenuItemButton;
    private javax.swing.JLabel deliveryDirLabel;
    private javax.swing.JLabel hiLabel;
    private javax.swing.JLabel managerLabel;
    private javax.swing.JTable menuDirTable;
    private javax.swing.JLabel menuItemName;
    private javax.swing.JLabel menuItemName1;
    private javax.swing.JTextField menuItemTextF;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel restaurantNameLabel;
    private javax.swing.JButton saveMenuItemsButton;
    // End of variables declaration//GEN-END:variables
}
